#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# Copyright (C) 2005-2006 Juan David Ibáñez Palomar <jdavid@itaapy.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

# Import from the Standard Library
from ConfigParser import RawConfigParser
from optparse import OptionParser

# Import from itools
import itools
from itools import uri
from itools import vfs
from itools.handlers.config import Config
from itools.vfs.database import DatabaseFS
from itools.cms.server import get_config, get_root, ask_confirmation
from itools.cms.server import Server


def update(parser, options, target):
    # Update the config file (renamed from "config.ini" to "config.conf")
    folder = vfs.open(target)
    if folder.exists('config.ini'):
        message = ('Update config file (will rename "config.ini" to'
                   ' "config.conf")? (y/N)')
        if ask_confirmation(message) is False:
            return
        print '  * Updating the configuration file...'
        # Load the old config file
        old_config = RawConfigParser()
        #old_config.add_section('instance')
        old_config.read(['%s/config.ini' % target])
        # Read the different options
        kw = {}
        for name in old_config.options('instance'):
            kw[name] = old_config.get('instance', name)
        # Remove the obsolete option "root"
        if 'root' in kw:
            if 'modules' in kw:
                del kw['root']
            else:
                kw['modules'] = kw['root']
        # Create the new config file
        new_config = Config(**kw)
        new_config.save_state_to('%s/config.conf' % target)
        # Remove the old confi file
        folder.remove('config.ini')

    # Update the database, add "database/.catalog.bak" and remove
    # "database.bak" (XXX remove for 0.16)
    if folder.exists('database.bak'):
        message = ('Update database (will remove "database.bak" and add '
                   '"database/.catalog.bak")? (y/N)')
        if ask_confirmation(message) is False:
            return
        print '  * Removing "database.bak"...'
        folder.remove('database.bak')
        print '  * Adding "database/.catalog.bak"...'
        folder.copy('database/.catalog', 'database/.catalog.bak')

    # Build the server object
    server = Server(target)
    target = server.target
    root = server.root

    instance_version = root.get_property('version')
    class_version = root.class_version
    if instance_version == class_version:
        print 'The instance is up-to-date (version: %s).' % instance_version
    elif instance_version > class_version:
        print 'WARNING: the instance (%s) is newer! than the class (%s)' \
              % (instance_version, class_version)
    else:
        message = 'Update instance from version %s to version %s (y/N)? ' \
                  % (instance_version, class_version)
        if ask_confirmation(message) is True:
            print 'Updating...'
            try:
                root.update()
            except:
                # Restore from backup
                DatabaseFS.rollback(server.database)
                raise
            # Update backup
            DatabaseFS.commit(server.database)



if __name__ == '__main__':
    # The command line parser
    usage = '%prog TARGET'
    version = 'itools %s' % itools.__version__
    description = ('Updates the TARGET itools.cms instance (if needed). Use'
                   ' this command when upgrading to a new version of itools.')
    parser = OptionParser(usage, version=version, description=description)

    options, args = parser.parse_args()
    if len(args) != 1:
        parser.error('incorrect number of arguments')

    target = args[0]

    # Action!
    update(parser, options, target)
