#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# Copyright (C) 2006 Juan David Ibáñez Palomar <jdavid@itaapy.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Import from the Standard Library
from optparse import OptionParser

# Import from itools
import itools
from itools import vfs
from itools.cms.server import ask_confirmation


def finish_commit(folder):
    """Continue to replace resources by their new state"""
    for name in folder.get_names():
        if name == '.catalog':
            if folder.exists('.catalog.bak'):
                folder.remove('.catalog.bak')
            folder.copy(name, '.catalog.bak')
        elif name == '.catalog.bak':
            continue
        elif folder.is_folder(name):
            subfolder = folder.open(name)
            finish_commit(subfolder)
        elif name[0] == '~':
            marker = name[-3:]
            if marker == 'tmp' or marker == 'add':
                original = name[1:-4]
                folder.move(name, original)
            elif marker == 'del':
                folder.remove(name)



def finish_rollback(folder):
    """Replace resources by backups"""
    for name in folder.get_names():
        if name == '.catalog':
            if folder.exists(name):
                folder.remove(name)
            folder.copy('.catalog.bak', name)
        elif name == '.catalog.bak':
            continue
        elif folder.is_folder(name):
            subfolder = folder.open(name)
            finish_rollback(subfolder)
        elif name[0] == '~':
            marker = name[-3:]
            if marker == 'tmp' or marker == 'add':
                folder.remove(name)
            elif marker == 'del':
                original = name[1:-4]
                folder.move(name, original)



def restore(parser, options, target):
    database = vfs.open(target).open('database')
    state = open('%s/state' % target).read()
    if state == 'OK':
        print 'Everything seems fine.'
    elif state == 'START':
        message = 'Restore database from backup (y/N)? '
        if ask_confirmation(message) is True:
            print '  * Restoring...',
            finish_rollback(database)
            open('%s/state' % target, 'w').write('OK')
            print 'DONE'
    elif state == 'COMMIT':
        message = 'Commit disrupted, continue (y/N)? '
        if ask_confirmation(message) is True:
            print '  * Commiting...',
            finish_commit(database)
            open('%s/state' % target, 'w').write('OK')
            print 'DONE'
    elif state == 'ROLLBACK':
        message = 'Rollback disrupted, continue (y/N)? '
        if ask_confirmation(message) is True:
            print '  * Rolling back...',
            finish_rollback(database)
            open('%s/state' % target, 'w').write('OK')
            print 'DONE'
    else:
        print 'PANIC: unknown database state'



if __name__ == '__main__':
    # The command line parser
    usage = '%prog TARGET'
    version = 'itools %s' % itools.__version__
    description = ('Restore the TARGET itools.cms instance if broken. To be'
                   ' used after a crash.')
    parser = OptionParser(usage, version=version, description=description)

    options, args = parser.parse_args()
    if len(args) != 1:
        parser.error('incorrect number of arguments')

    target = args[0]

    # Action!
    restore(parser, options, target)
