PACKAGES_DB = {
#    '':    {'E': '', 'M': ''},
    'AptUrl':                {'E': 'apturl', 'M': 'AptUrl'},
    'ccsm':                  {'E': 'ccsm', 'M': 'ccm'},
    'CodeHack':              {'E': 'CodeHack', 'M': 'codehack'},
    'logilab-common':        {'E': 'logilab_common', 'M': 'logilab'},
    'logilab-astng':         {'E': 'logilab_astng', 'M': 'logilab.astng'},
    'Magic file extensions': {'E': 'Magic_file_extensions', 'M': 'magic'},
    'Onboard':               {'E': 'onboard', 'M': 'Onboard'},
    'PyOpenGL':              {'E': 'PyOpenGL', 'M': 'OpenGL'},
    'pyOpenSSL':             {'E': 'pyOpenSSL', 'M': 'OpenSSL'},
    'pysqlite2':             {'E': 'pysqlite', 'M': 'pysqlite2'},
    'python-apt':            {'E': 'python_apt', 'M': 'apt'},
    'Reportlab':             {'E': 'Reportlab', 'M': 'reportlab'},
#    'Twisted Core':          {'E': 'Twisted_Core', 'M': 'twisted'},
    'Twisted Core':          {'E': 'Twisted', 'M': 'twisted'},
    'Twisted Web':           {'E': 'Twisted_Web', 'M': 'twisted.web'},
}
