PACKAGES_DB = (
#    .egg-info                version  module name
    ('apturl',                '*',     'AptUrl'),
    ('ccsm',                  '*',     'ccm'),
    ('CodeHack',              '*',     'codehack'),
    ('dnspython',             '*',     'dns'),
    ('java_config',           '1*',    'java_config'),
    ('java_config',           '2*',    'java_config_2'),
    ('logilab_common',        '*',     'logilab'),
    ('logilab_astng',         '*',     'logilab.astng'),
    ('Magic_file_extensions', '*',     'magic'),
    ('onboard',               '*',     'Onboard'),
    ('PyOpenGL',              '*',     'OpenGL'),
    ('pyOpenSSL',             '*',     'OpenSSL'),
    ('pysqlite',              '*',     'pysqlite2'),
    ('python_apt',            '*',     'apt'),
    ('Reportlab',             '*',     'reportlab'),
    ('Twisted',               '*',     'twisted'),
    ('Twisted_Web',           '*',     'twisted.web'),
)
